name: yewtube

environment:
  sdk: ^3.0.6

dependencies:
  angel3_configuration: ^8.0.0
  angel3_file_service: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_jael: ^8.0.0
  angel3_serialize: ^8.0.0
  angel3_static: ^8.0.0
  angel3_validate: ^8.0.0
  uuid: ^3.0.7
dev_dependencies:
  angel3_serialize_generator: ^8.0.1
  build_runner: ^2.4.6
